name: Setup CUDA Toolkit
description: Install and configure CUDA Toolkit

inputs:
  cuda-version:
    description: CUDA Toolkit version to install
    required: false
    default: "13.2.0"

runs:
  using: composite
  steps:
    - name: Install CUDA toolkit
      uses: Jimver/cuda-toolkit@v0.2.35
      id: cuda-toolkit
      with:
        cuda: ${{ inputs.cuda-version }}

    - name: Print CUDA version
      shell: bash
      run: echo "Installed CUDA version is: ${{ steps.cuda-toolkit.outputs.cuda }}"

    - name: Print CUDA install location
      shell: bash
      run: echo "CUDA install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"

    - name: Check nvcc
      shell: bash
      run: nvcc -V
