//! Low-level FFI bindings to Povu C API
//!
//! This module contains the raw C bindings generated by bindgen.
//! Most users should use the high-level API in the parent module instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

impl Default for PovuError {
    fn default() -> Self {
        PovuError {
            code: 0,
            message: std::ptr::null_mut(),
        }
    }
}
