name: Build (Ubuntu Cuda)
# Test build for Ubuntu with C++17 & CMake

on:
  # branch glob syntax https://stackoverflow.com/a/57903434
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-22.04 # gcc 11 is default on 22.04

    strategy:
      matrix:
        build_type: [Release, Debug]

    name: Build ${{ matrix.build_type }}

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print compiler version
        run: |
          gcc --version
          g++ --version

      - name: Setup Cuda
        uses: ./.github/actions/setup-cuda

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
          -DENABLE_CUDA=ON \
          -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build --config ${{ env.CMAKE_BUILD_TYPE }}

