name: Tests

on:
  # branch glob syntax https://stackoverflow.com/a/57903434
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release, Debug]

    name: Test ${{ matrix.build_type }}

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GCC 11
        uses: ./.github/actions/setup-gcc

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -DPOVU_ENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build

      # Uncomment and adjust when you're ready to run tests
      # - name: Test
      #   working-directory: ${{ github.workspace }}/build
      #   run: ctest -C ${{ env.CMAKE_BUILD_TYPE }}
      #
      - name: Test
        # working-directory: ${{ github.workspace }}/build
        run: |
          ctest --verbose --test-dir ${{ github.workspace }}/build --output-on-failure

